FROM node:20-alpine

RUN corepack enable && corepack prepare pnpm@9.15.4 --activate
WORKDIR /app

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY apps/client/package.json apps/client/
COPY packages/shared/package.json packages/shared/

RUN pnpm install --frozen-lockfile --filter @baia/client...

COPY packages/shared ./packages/shared
COPY apps/client ./apps/client

WORKDIR /app/apps/client

EXPOSE 3000

CMD ["pnpm", "run", "dev"]
